//------------------------------------------------------------------------------
// <Auto-Generated>
//   Powered By S. L. Lee, ContactQQ：121283087
// </Auto-Generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Remoting.Messaging;
using ShSoft.Framework2015.AOP.Models.Entities;
using ShSoft.Framework2015.Common.PoweredByLee;

namespace ShSoft.Framework2015.LogSite.Model.RunningLogs
{
    /// <summary>
    /// 程序日志数据访问层类
    /// </summary>
    public class RunningLogDal
    {
        #region 00.单例构造器

        /// <summary>
        /// SQL工具
        /// </summary>
        private static readonly SqlHelper _SqlHelper;

        /// <summary>
        /// 静态构造器
        /// </summary>
        static RunningLogDal()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["LogConnection"].ConnectionString;

            //初始化SQL工具
            _SqlHelper = new SqlHelper(connectionString);
        }

        /// <summary>
        /// 创建对象静态方法
        /// </summary>
        /// <returns>RunningLogDal实例</returns>
        public static RunningLogDal CreateInstance()
        {
            RunningLogDal exceptionLogDal = CallContext.GetData(typeof(RunningLogDal).Name) as RunningLogDal;
            if (exceptionLogDal == null)
            {
                exceptionLogDal = new RunningLogDal();
                CallContext.SetData(typeof(RunningLogDal).Name, exceptionLogDal);
            }
            return exceptionLogDal;
        }
        #endregion

        #region 01.删除方法（物理删除）
        /// <summary>
        /// 删除一个实体对象
        /// </summary>
        /// <param name="id">要删除的实体对象Id</param>
        /// <returns>受影响的行数</returns>
        public int PhysicalDelete(Guid id)
        {
            string sql = "DELETE FROM RunningLogs WHERE Id = @Id";
            SqlParameter arg = new SqlParameter("@Id", id);
            return _SqlHelper.ExecuteNonQuery(sql, arg);
        }
        #endregion

        #region 02.根据日志Id、开始时间、结束时间查询日志记录条数
        /// <summary>
        /// 根据日志Id、开始时间、结束时间查询日志记录条数
        /// </summary>
        /// <param name="logId">日志Id</param>
        /// <param name="startTime">开始时间</param>
        /// <param name="endTime">结束时间</param>
        /// <returns>符合条件的日志记录条数</returns>
        public int GetCount(Guid logId, string startTime, string endTime)
        {
            string sql = "SELECT COUNT(*) FROM dbo.RunningLogs WHERE 0 = 0";

            #region # 非空校验

            if (logId != Guid.Empty)
            {
                sql = string.Format("{0} AND Id = '{1}'", sql, logId);
            }

            if (!string.IsNullOrWhiteSpace(startTime))
            {
                sql = string.Format("{0} AND StartTime >= '{1}'", sql, startTime);
            }

            if (!string.IsNullOrWhiteSpace(endTime))
            {
                sql = string.Format("{0} AND StartTime <= '{1}'", sql, endTime);
            }

            #endregion

            return (int)_SqlHelper.ExecuteScalar(sql);
        }
        #endregion

        #region 03.根据日志Id、开始时间、结束时间查询日志列表
        /// <summary>
        /// 根据日志Id、开始时间、结束时间查询日志列表
        /// </summary>
        /// <param name="start">起始行</param>
        /// <param name="end">结束行</param>
        /// <param name="logId">日志Id</param>
        /// <param name="startTime">开始时间</param>
        /// <param name="endTime">结束时间</param>
        /// <returns>日志列表</returns>
        public List<RunningLog> GetModelList(int start, int end, Guid logId, string startTime, string endTime)
        {
            List<RunningLog> list = new List<RunningLog>();
            string sql = "SELECT *, ROW_NUMBER() OVER(ORDER BY StartTime DESC) AS RowIndex  FROM dbo.RunningLogs WHERE 0 = 0";

            #region # 非空校验

            if (logId != Guid.Empty)
            {
                sql = string.Format("{0} AND Id = '{1}'", sql, logId);
            }

            if (!string.IsNullOrWhiteSpace(startTime))
            {
                sql = string.Format("{0} AND StartTime >= '{1}'", sql, startTime);
            }

            if (!string.IsNullOrWhiteSpace(endTime))
            {
                sql = string.Format("{0} AND StartTime <= '{1}'", sql, endTime);
            }

            #endregion

            //分页处理
            sql = string.Format("SELECT * FROM ({0}) AS T WHERE T.RowIndex >= @Start AND T.RowIndex <= @End", sql);

            SqlParameter[] args = {
                new SqlParameter("@Start", start),
                new SqlParameter("@End", end)
            };

            using (SqlDataReader reader = _SqlHelper.ExecuteReader(sql, args))
            {
                while (reader.Read())
                {
                    list.Add(this.ToModel(reader));
                }
            }
            return list;
        }
        #endregion

        #region 04.查看日志明细
        /// <summary>
        /// 查看日志明细
        /// </summary>
        /// <param name="id">标识Id</param>
        /// <returns>日志明细</returns>
        public RunningLog GetModel(Guid id)
        {
            string sql = "SELECT * FROM RunningLogs WHERE Id = @Id";
            using (SqlDataReader reader = _SqlHelper.ExecuteReader(sql, new SqlParameter("@Id", id)))
            {
                if (reader.Read())
                {
                    return this.ToModel(reader);
                }
                return null;
            }
        }
        #endregion

        #region 05.根据SqlDataReader对象返回实体对象方法
        /// <summary>
        /// 根据SqlDataReader对象返回实体对象方法
        /// </summary>
        /// <param name="reader">SqlDataReader对象</param>
        /// <returns>实体</returns>
        private RunningLog ToModel(SqlDataReader reader)
        {
            RunningLog runningLog = new RunningLog
            {
                Id = (Guid)this.ToModelValue(reader, "Id"),
                Namespace = (string)this.ToModelValue(reader, "Namespace"),
                ClassName = (string)this.ToModelValue(reader, "ClassName"),
                MethodName = (string)this.ToModelValue(reader, "MethodName"),
                MethodType = (string)this.ToModelValue(reader, "MethodType"),
                ArgsJson = (string)this.ToModelValue(reader, "ArgsJson"),
                ReturnValue = (string)this.ToModelValue(reader, "ReturnValue"),
                ReturnValueType = (string)this.ToModelValue(reader, "ReturnValueType"),
                UserId = (Guid)this.ToModelValue(reader, "UserId"),
                UserName = (string)this.ToModelValue(reader, "UserName"),
                StartTime = (DateTime)this.ToModelValue(reader, "StartTime"),
                StartTimeString = Convert.ToDateTime(this.ToModelValue(reader, "StartTime")).ToString("yyyy-MM-dd HH:mm:ss.fff"),
                EndTime = (DateTime)this.ToModelValue(reader, "EndTime"),
                IPAddress = (string)this.ToModelValue(reader, "IPAddress"),
                EndTimeString = Convert.ToDateTime(this.ToModelValue(reader, "EndTime")).ToString("yyyy-MM-dd HH:mm:ss.fff")
            };
            return runningLog;
        }
        #endregion

        #region 06.数据库值转C#值空值处理
        /// <summary>
        /// 数据库值转C#值空值处理
        /// </summary>
        /// <param name="reader">IDataReader对象</param>
        /// <param name="columnName">列名</param>
        /// <returns>C#值</returns>
        private object ToModelValue(IDataReader reader, string columnName)
        {
            if (reader.IsDBNull(reader.GetOrdinal(columnName)))
            {
                return null;
            }
            return reader[columnName];
        }

        #endregion
    }
}
