//------------------------------------------------------------------------------
// <Auto-Generated>
//   Powered By S. L. Lee, ContactQQ：121283087
// </Auto-Generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ShSoft.Framework2015.LogSite.Model.Format;

namespace ShSoft.Framework2015.LogSite.Model
{
    /// <summary>
    /// Menus实体类
    /// </summary>
    [Serializable]
    public class Menu
    {
        /// <summary>
        /// 标识Id
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// 上级菜单
        /// </summary>
        [DisplayName("上级菜单")]
        public int PId { get; set; }

        /// <summary>
        /// 上级菜单
        /// </summary>
        [DisplayName("上级菜单")]
        public string PName { get; set; }

        /// <summary>
        /// 菜单名称
        /// </summary>
        [DisplayName("菜单名称")]
        public string MenuName { get; set; }

        /// <summary>
        /// 链接地址
        /// </summary>
        [DisplayName("链接地址")]
        public string Url { get; set; }

        /// <summary>
        /// 是否是链接
        /// </summary>
        [DisplayName("是否是链接")]
        public bool? IsLink { get; set; }

        /// <summary>
        /// 菜单等级
        /// </summary>
        [DisplayName("菜单等级")]
        public int Level { get; set; }

        /// <summary>
        /// 排序
        /// </summary>
        [DisplayName("排序")]
        public int? Sort { get; set; }

        #region 02.方法——菜单实体转换为树形节点
        /// <summary>
        /// 菜单实体转换为树形节点方法
        /// </summary>
        /// <returns>树形节点</returns>
        public TreeModel ToTreeNode()
        {
            //返回TreeModel
            return new TreeModel()
            {
                id = this.Id,
                text = this.MenuName,
                state = "open",
                attributes = new { href = this.Url, isLink = this.IsLink == true ? 1 : 0 },
                @checked = false
            };
        }
        #endregion
    }
}
